title: IARA
description: jojs
template:
  repo: iara-template
  name: iara
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
